twitter-to-kafka-service:
  twitter-keywords:
    - JAVA
    - SPRING
    - BOOT
    - TWITTER
    - KAFKA
  welcome-message: "Hello service"
  enable-mock-tweets: true
  mock-min-tweet-length: 5
  mock-max-tweet-length: 15
  mock-sleep-ms: 10000

retry-config:
  initial-interval-ms: 1000
  max-interval-ms: 10000
  multipliers: 2.0
  max-attempts: 3
  sleep-time-ms: 2000

kafka-config:
  bootstrap-servers: localhost:19092, localhost:29092, localhost:39092
  schema-registry-url: http://localhost:8081
  schema-registry-url-key: schema.registry.url
  topic-name: twitter-topic
  topic-names-to-create:
    - twitter-topic
  num-of-partitions: 3
  replication-facator: 3

kafka-producer-config:
  key-serialization-class: org.apache.kafka.common.serialization.LongSerializer
  value-serialization-class: io.confluent.kafka.serializers.KafkaAvroSerializer
  acks: all
  compression-type: snappy
  batch-size: 16384
  batch-size-boost-factor: 100
  linger-ms: 5
  request-timeout-ms: 60000
  retry-count: 5

